---
      
    - name: file creation
     
      file:
        path: /home/ec2-user/tars
        state: directory

    - name: Download Java
      
      get_url:
        url: "{{download_url}}"
        dest: "{{java_archive}}"

    - name: Unpack archive

      unarchive: src=/home/ec2-user/tars/jdk-12.0.1-linux-x64.tar.gz dest=/home/ec2-user/tars copy=no

    - name: Fix ownership
      file: state=directory path={{java_name}} owner=ec2-user group=ec2-user recurse=yes

    - name: Make Java available for system
      command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

    - name: Set/Configure JAVA_HOME in environment variables 
      shell: "echo 'export JAVA_HOME={{java_name}}\n export PATH=$JAVA_HOME/bin:$PATH' > {{java_env_file}}"
    
    - name: Exports/Run java env file for make JAVA_HOME available globally
      shell: "source {{java_env_file}}"

    
