---
  - name: file creation
  
    file:

     path: /home/ec2-user/tars
     state: directory  
  - name: Download Tomcat
    get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz dest=/home/ec2-user/tars/apache-tomcat-7.0.61.tar.gz

  - name: Extract archive
    unarchive: src=/home/ec2-user/tars/apache-tomcat-7.0.61.tar.gz dest=/home/ec2-user/tars
  - name: start appache-tomcat-7.0.61
    shell: /home/ec2-user/tars/apache-tomcat-7.0.61/bin/startup.sh
  - name: download war file
    get_url: url=https://drive.google.com/file/d/1ArPA8ypfBEb-5OAtjcjlcolYQvCxzoX7/view?usp=sharing dest=/home/ec2-user/tars
  - name: copy war file
    shell: cp /home/ec2-user/tars/view /home/ec2-user/tars/apache-tomcat-7.0.61/webapps
