---
  - name: file creation

    file:
      path: /home/ec2-user/tars
      state: directory
    
  - name: Download Tomcat
    get_url: 
      url:  http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz
      dest: /home/ec2-user/tars/apache-tomcat-7.0.61.tar.gz

  - name: Extract archive
    unarchive:
      src: "{{tomcat_archive}}"
      dest: "{{download_folder}}"
      remote_src: yes
  

