---
  - name: file creation
  
    file:

     path: /home/ec2-user/tars
     state: directory
       
  - name: Download Tomcat
    get_url: 
      url: "{{download_url}}"
      dest: "{{tomcat_archive}}"
  - name: Extract archive
    unarchive:
      src: "{{tomcat_archive}}"
      dest: "{{download_folder}}"
      remote_src: yes
  - name: start appache-tomcat-7.0.61
    shell: "{{tomcat_name1}}"
  - name: downloading war
    get_url:
      url: "{{download_url1}}"
      dest: "{{war_download}}"
